# Generated by Django 2.2 on 2019-04-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True)),
                ('date_end', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='states',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='states',
            name='date_start',
        ),
        migrations.AddField(
            model_name='states',
            name='sprint',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='data.Sprint'),
        ),
    ]
