# Generated by Django 2.2 on 2019-04-27 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20190427_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_ach', models.CharField(choices=[('PAL', 'per_from_all_tests'), ('PFB', 'per_from_builds'), ('NC', 'num_commits'), ('POT', 'per_over_tests'), ('NOUT', 'num_of_unclosed_tasks')], default='PAL', max_length=4)),
                ('sprint', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achieves', to='data.Sprint')),
                ('user', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achieves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
