# Generated by Django 2.2 on 2019-04-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_achieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
